version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:12.13.0

    working_directory: ~/repo

    steps:
      - checkout

      - run: echo $(find ./patches -type f -exec md5sum {} \; | md5sum | cut -d' ' -f1) >> PATCH_CACHE_KEY

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "PATCH_CACHE_KEY" }}-{{ checksum "package-lock.json" }}

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "PATCH_CACHE_KEY" }}-{{ checksum "package-lock.json" }}

      # run typecheck
      - run: npm run typecheck
      # run linting check
      - run: npm run lint
      # run tests
      - run:
          name: Run Tests
          no_output_timeout: 30m
          command: npm run test:build

workflows:
  version: 2
  test:
    jobs:
      - test
